import type { ProjectMeta } from "@/lib/types";

export const projects: ProjectMeta[] = [
  {
    slug: "01-abnormal-results",
    number: 1,
    title: "Abnormal Lab Result Predictor",
    tagline: "Classify lab results as normal or abnormal using patient demographics and test history.",
    difficulty: "Beginner",
    status: "complete",
    clients: ["Upcare Diagnostics", "PUDC", "One Health Medical"],
    tables: ["patients", "patient_service_results", "patient_services"],
    techniques: ["Logistic Regression", "Random Forest", "XGBoost"],
    keyMetric: { value: "0.61", label: "AUC-ROC (real)" },
    color: "bg-[#ECF2FE]",
  },
  {
    slug: "02-turnaround-time",
    number: 2,
    title: "Lab Turnaround Time Predictor",
    tagline: "Predict service completion delays before they affect patient experience.",
    difficulty: "Beginner",
    status: "in-progress",
    clients: ["All Clients"],
    tables: ["patient_services", "patients", "orders"],
    techniques: ["Linear Regression", "Random Forest Regressor", "Gradient Boosting"],
    keyMetric: { value: "34%", label: "Delay Reduction" },
    color: "bg-[#ECF2FE]",
  },
  {
    slug: "03-patient-segmentation",
    number: 3,
    title: "Patient Segmentation",
    tagline: "Cluster patients into behavioral groups to drive targeted outreach and operations.",
    difficulty: "Intermediate",
    status: "in-progress",
    clients: ["Upcare Diagnostics", "PUDC"],
    tables: ["patients", "orders", "order_items", "patient_services"],
    techniques: ["K-Means Clustering", "Hierarchical Clustering", "PCA"],
    keyMetric: { value: "5", label: "Distinct Segments" },
    color: "bg-[#F7F3DF]",
  },
  {
    slug: "04-test-bundles",
    number: 4,
    title: "Test Bundle Analysis",
    tagline: "Identify which lab tests are frequently ordered together to inform package design.",
    difficulty: "Beginner",
    status: "in-progress",
    clients: ["All Clients"],
    tables: ["order_items", "patient_services"],
    techniques: ["Association Rule Mining", "Apriori Algorithm", "Co-occurrence Heatmaps"],
    keyMetric: { value: "12", label: "Bundles Found" },
    color: "bg-[#ECF2FE]",
  },
  {
    slug: "05-revenue-anomalies",
    number: 5,
    title: "Revenue & Discount Anomaly Detection",
    tagline: "Surface unusual discount patterns and revenue irregularities across branches.",
    difficulty: "Intermediate",
    status: "in-progress",
    clients: ["All Clients"],
    tables: ["orders", "order_items"],
    techniques: ["Isolation Forest", "Z-score Detection", "DBSCAN"],
    keyMetric: { value: "2.3%", label: "Anomaly Rate" },
    color: "bg-[#F7F3DF]",
  },
  {
    slug: "06-ticket-intelligence",
    number: 6,
    title: "Support Ticket Intelligence",
    tagline: "Classify support tickets and predict SLA breaches before they happen.",
    difficulty: "Intermediate",
    status: "in-progress",
    clients: ["Kalix"],
    tables: ["patient_services"],
    techniques: ["NLP", "Text Classification", "SLA Breach Prediction"],
    keyMetric: { value: "332", label: "Tickets Analyzed" },
    color: "bg-[#F7F3DF]",
  },
  {
    slug: "07-soap-nlp",
    number: 7,
    title: "SOAP Notes NLP Analysis",
    tagline: "Extract clinical insights from SOAP notes using topic modeling and entity recognition.",
    difficulty: "Advanced",
    status: "placeholder",
    clients: ["ARDI Health Services"],
    tables: ["patient_services"],
    techniques: ["TF-IDF", "LDA Topic Modeling", "Named Entity Recognition"],
    keyMetric: { value: "—", label: "In Development" },
    color: "bg-[#FCE4EC]",
  },
  {
    slug: "08-radiology-parser",
    number: 8,
    title: "Radiology Impression Parser",
    tagline: "Parse multilingual radiology findings into structured normal/abnormal classifications.",
    difficulty: "Advanced",
    status: "placeholder",
    clients: ["Klinik dr. Hondo Supeno"],
    tables: ["patient_service_results"],
    techniques: ["Multilingual NLP", "Regex Extraction", "Bahasa Indonesia Processing"],
    keyMetric: { value: "—", label: "In Development" },
    color: "bg-[#FCE4EC]",
  },
  {
    slug: "09-cross-client-benchmark",
    number: 9,
    title: "Cross-Client Operational Benchmarking",
    tagline: "Compare performance metrics across anonymized healthcare organizations in PH and Indonesia.",
    difficulty: "Intermediate",
    status: "complete",
    clients: ["All Clients"],
    tables: ["patient_services", "orders", "patient_service_results"],
    techniques: ["Statistical Comparison", "ANOVA", "Multi-source Normalization"],
    keyMetric: { value: "13", label: "Clients Pooled" },
    color: "bg-[#F7F3DF]",
  },
];
