import type { ProjectMeta } from "@/lib/types";

export const projects: ProjectMeta[] = [
  {
    slug: "01-abnormal-results",
    number: 1,
    title: "Abnormal Lab Result Predictor",
    tagline: "Classify lab results as normal or abnormal using patient demographics and test history.",
    difficulty: "Beginner",
    status: "complete",
    clients: ["Upcare Diagnostics", "PUDC", "One Health Medical"],
    tables: ["patients", "patient_service_results", "patient_services"],
    techniques: ["Logistic Regression", "Random Forest", "Cross-Validation"],
    keyMetric: { value: "0.61", label: "AUC-ROC (real)" },
    color: "bg-[#ECF2FE]",
  },
  {
    slug: "02-turnaround-time",
    number: 2,
    title: "Lab Turnaround Time Analysis",
    tagline: "Measure real turnaround time where labs capture it — and expose the network-wide measurement gap.",
    difficulty: "Beginner",
    status: "complete",
    clients: ["All Clients"],
    tables: ["patient_services"],
    techniques: ["Timestamp Analysis", "Coverage Audit", "Distribution Analysis"],
    keyMetric: { value: "3 / 13", label: "Labs Measure TAT" },
    color: "bg-[#ECF2FE]",
  },
  {
    slug: "03-patient-segmentation",
    number: 3,
    title: "Patient Segmentation",
    tagline: "Cluster patients into behavioral groups — pending full patient visit history.",
    difficulty: "Intermediate",
    status: "placeholder",
    clients: ["Upcare Diagnostics", "PUDC"],
    tables: ["patients", "orders", "order_items", "patient_services"],
    techniques: ["K-Means Clustering", "PCA", "Feature Engineering"],
    keyMetric: { value: "—", label: "Limited Data" },
    color: "bg-[#F7F3DF]",
  },
  {
    slug: "04-test-bundles",
    number: 4,
    title: "Test Bundle Analysis",
    tagline: "Identify which lab tests are frequently ordered together to inform package design.",
    difficulty: "Beginner",
    status: "complete",
    clients: ["All Clients"],
    tables: ["order_items", "patient_services"],
    techniques: ["Association Rule Mining", "Co-occurrence", "Lift Analysis"],
    keyMetric: { value: "18", label: "Strong Pairs" },
    color: "bg-[#ECF2FE]",
  },
  {
    slug: "05-revenue-anomalies",
    number: 5,
    title: "Revenue & Discount Anomaly Detection",
    tagline: "Surface unusual discount patterns and revenue irregularities across orders.",
    difficulty: "Intermediate",
    status: "complete",
    clients: ["All Clients"],
    tables: ["orders"],
    techniques: ["Isolation Forest", "Z-score Detection", "Ensemble Agreement"],
    keyMetric: { value: "2.2%", label: "Anomaly Rate" },
    color: "bg-[#F7F3DF]",
  },
  {
    slug: "06-ticket-intelligence",
    number: 6,
    title: "Support Ticket Resolution Analysis",
    tagline: "Analyze priority mix and resolution time across real support tickets.",
    difficulty: "Intermediate",
    status: "complete",
    clients: ["Kalix"],
    tables: ["patient_services"],
    techniques: ["Resolution-Time Analysis", "Priority Triage", "Workflow Timestamps"],
    keyMetric: { value: "9.0h", label: "Median Resolution" },
    color: "bg-[#F7F3DF]",
  },
  {
    slug: "07-soap-nlp",
    number: 7,
    title: "SOAP Notes NLP Analysis",
    tagline: "Extract clinical insights from SOAP notes using topic modeling and entity recognition.",
    difficulty: "Advanced",
    status: "placeholder",
    clients: ["ARDI Health Services"],
    tables: ["patient_services"],
    techniques: ["TF-IDF", "LDA Topic Modeling", "Named Entity Recognition"],
    keyMetric: { value: "—", label: "In Development" },
    color: "bg-[#FCE4EC]",
  },
  {
    slug: "08-radiology-parser",
    number: 8,
    title: "Radiology Impression Parser",
    tagline: "Parse multilingual radiology findings into structured normal/abnormal classifications.",
    difficulty: "Advanced",
    status: "placeholder",
    clients: ["Klinik dr. Hondo Supeno"],
    tables: ["patient_service_results"],
    techniques: ["Multilingual NLP", "Regex Extraction", "Bahasa Indonesia Processing"],
    keyMetric: { value: "—", label: "In Development" },
    color: "bg-[#FCE4EC]",
  },
  {
    slug: "09-cross-client-benchmark",
    number: 9,
    title: "Cross-Client Operational Benchmarking",
    tagline: "Compare performance metrics across anonymized healthcare organizations in PH and Indonesia.",
    difficulty: "Intermediate",
    status: "complete",
    clients: ["All Clients"],
    tables: ["patient_services", "orders", "patient_service_results"],
    techniques: ["Statistical Comparison", "Schema Normalization", "Rate Analysis"],
    keyMetric: { value: "13", label: "Clients Pooled" },
    color: "bg-[#F7F3DF]",
  },
];
