export interface ProjectDetail {
  businessProblem: { headline: string; paragraphs: string[]; cards: { label: string; value: string }[] };
  dataSources: { headline: string; description: string; tables: { name: string; fields: string[]; note: string; primary?: boolean }[] };
  methodology: { headline: string; description: string; steps: { step: string; title: string; desc: string }[] };
  analysis: { headline: string; description: string; kpis: { value: string; label: string; sub: string; color: string }[]; charts: { title: string; subtitle: string; unit?: string; data?: { label: string; value: number; n?: number }[] }[] };
  insights: { headline: string; items: { title: string; desc: string }[] };
  future: { headline: string; items: { title: string; desc: string }[] };
}

export const projectDetails: Record<string, ProjectDetail> = {

  "01-abnormal-results": {
    businessProblem: {
      headline: "Given a patient's age, test type, and client, can we predict an abnormal result?",
      paragraphs: ["Across the 13 synthetic clients, 17293 labeled results were generated, of which 36.4% fall outside their reference range.", "This project frames an early-flagging classifier: at registration we know the patient's age, the ordered test, and the client — can that predict whether the result will come back abnormal?"],
      cards: [{ label: "Problem Type", value: "Binary Classification" },
        { label: "Target", value: "is_abnormal (0 / 1)" },
        { label: "Best AUC", value: "0.78 (Random Forest)" }],
    },
    dataSources: {
      headline: "Three tables across all 13 synthetic clients.",
      description: "Labels are derived from reference ranges in the synthetic results table; features come from demographics and service metadata.",
      tables: [{ name: "patient_service_results", fields: ["number_value", "ref_range_min", "ref_range_max", "unit"], note: "Source of the abnormal label", primary: true },
        { name: "patient_services", fields: ["service_name", "status", "created_at"], note: "Test type feature" },
        { name: "patients", fields: ["age", "sex"], note: "Demographic features" }],
    },
    methodology: {
      headline: "Label from ranges, engineer features, train, validate.",
      description: "The abnormal label is rule-based; the model never sees the reference range as an input (no leakage).",
      steps: [{ step: "01", title: "Label Generation", desc: "is_abnormal = 1 when number_value falls outside ref_range_min / ref_range_max." },
        { step: "02", title: "Feature Engineering", desc: "Age, sex, encoded service_name, and client. Reference ranges excluded from inputs." },
        { step: "03", title: "Model Training", desc: "Logistic Regression baseline, then Random Forest (200 trees). 80/20 stratified split." },
        { step: "04", title: "Validation", desc: "ROC-AUC as primary metric; precision and recall reported on the abnormal class." }],
    },
    analysis: {
      headline: "Test type and age drive abnormality.",
      description: "Results computed on the synthetic dataset. The model recovers the engineered signal cleanly.",
      kpis: [{ value: "0.78", label: "AUC Score", sub: "Random Forest", color: "#27AE60" },
        { value: "68%", label: "Precision", sub: "Abnormal class", color: "#1566FF" },
        { value: "52%", label: "Recall", sub: "Abnormal class", color: "#1566FF" },
        { value: "36.4%", label: "Abnormal Rate", sub: "All services", color: "#C7AA50" }],
      charts: [{ title: "Abnormal Rate by Test Type", subtitle: "Share of results outside reference range", unit: "%", data: [{ label: "Kimia Klinik", value: 61.6, n: 292 }, { label: "Lipid Panel", value: 59.8, n: 3079 }, { label: "HbA1c", value: 53.9, n: 3117 }, { label: "SGPT/ALT", value: 36.5, n: 353 }, { label: "Fasting Blood Sugar", value: 36.1, n: 1947 }, { label: "FT3", value: 30.5, n: 1308 }] }, { title: "Top Predictive Features", subtitle: "Random Forest importance (top 6)", unit: "", data: [{ label: "age", value: 50.0 }, { label: "Lipid Panel", value: 33.3 }, { label: "HbA1c", value: 25.0 }, { label: "Urinalysis", value: 20.0 }, { label: "Complete Blood Count", value: 16.7 }, { label: "BUN", value: 14.3 }] }],
    },
    insights: {
      headline: "What the model shows.",
      items: [{ title: "Metabolic tests carry the highest abnormal rates", desc: "Lipid Panel, HbA1c, and fasting glucose top the abnormal-rate ranking — consistent with how the data was engineered around age and test type." },
        { title: "Age is the strongest demographic signal", desc: "Abnormality rises steadily with age, making it the dominant non-test feature." },
        { title: "Client adds a measurable but secondary effect", desc: "A learnable client offset means some locations run hotter than others — useful for routing review attention." },
        { title: "Reading note: these are synthetic outcomes", desc: "The 0.78 AUC reflects the signal deliberately built into the generator, not a real clinical discovery." }],
    },
    future: {
      headline: "What a production version would need.",
      items: [{ title: "Real labeled outcomes", desc: "Replace rule-based labels with clinician-confirmed abnormality on real data." },
        { title: "Per-test models", desc: "Separate models per test category would likely beat one global model." },
        { title: "Live inference", desc: "A scoring endpoint returning abnormality probability before processing." },
        { title: "Temporal validation", desc: "Time-based splits and periodic retraining for drift." }],
    },
  },

  "02-turnaround-time": {
    businessProblem: {
      headline: "Which services will be slow — and what drives the delay?",
      paragraphs: ["Turnaround time (TAT) is the gap between sample collection and result lock. Across the synthetic clients the median is 132 minutes over 18759 services.", "This project predicts TAT from operational features — weekday, hour, branch, test type, and client — to find where bottlenecks form."],
      cards: [{ label: "Problem Type", value: "Regression" },
        { label: "Target", value: "turnaround_minutes" },
        { label: "Model R²", value: "0.79" }],
    },
    dataSources: {
      headline: "Timestamp-rich service data across all 13 clients.",
      description: "TAT is derived from collected_at and locked_at, which the generator populates for every client.",
      tables: [{ name: "patient_services", fields: ["collected_at", "locked_at", "service_name", "status"], note: "Timestamps define TAT", primary: true },
        { name: "orders", fields: ["branch_ids", "created_at"], note: "Branch and volume context" },
        { name: "patients", fields: ["age", "sex"], note: "Demographic context" }],
    },
    methodology: {
      headline: "Engineer time features, model the drivers.",
      description: "The core work is turning raw timestamps into predictive features.",
      steps: [{ step: "01", title: "TAT Calculation", desc: "turnaround_minutes = locked_at - collected_at. Non-positive and extreme values removed." },
        { step: "02", title: "Feature Engineering", desc: "Weekday, hour-of-day, branch, encoded service, and client." },
        { step: "03", title: "Model Training", desc: "Random Forest Regressor (150 trees, depth 14). 80/20 split." },
        { step: "04", title: "Validation", desc: "MAE and R² on held-out data; weekday profile inspected for bias." }],
    },
    analysis: {
      headline: "Mondays and peak hours dominate delay.",
      description: "Computed on the synthetic dataset.",
      kpis: [{ value: "0.79", label: "Model R²", sub: "Random Forest", color: "#27AE60" },
        { value: "26min", label: "MAE", sub: "Mean Absolute Error", color: "#1566FF" },
        { value: "132min", label: "Median TAT", sub: "All services", color: "#475175" },
        { value: "1.6x", label: "Monday Slowdown", sub: "vs midweek", color: "#C7AA50" }],
      charts: [{ title: "Average TAT by Weekday", subtitle: "Minutes from collection to lock", unit: " min", data: [{ label: "Mon", value: 216 }, { label: "Tue", value: 141 }, { label: "Wed", value: 134 }, { label: "Thu", value: 139 }, { label: "Fri", value: 161 }, { label: "Sat", value: 106 }, { label: "Sun", value: 101 }] }],
    },
    insights: {
      headline: "What drives turnaround.",
      items: [{ title: "Monday is the predictable bottleneck", desc: "Average TAT spikes at week-start (216 min) versus ~134 midweek — weekend backlog clearing through Monday." },
        { title: "Collection hour matters", desc: "Samples taken in the 10–11am peak run slower than early-morning collections." },
        { title: "Branch effects are real", desc: "The same test shows different TAT by branch, pointing to staffing rather than test complexity." },
        { title: "Reading note: synthetic timings", desc: "The R² of 0.79 reflects engineered weekday/hour/branch effects, not a measured operation." }],
    },
    future: {
      headline: "Production improvements.",
      items: [{ title: "Real-time SLA alerts", desc: "Flag services predicted to breach before they do." },
        { title: "Per-branch models", desc: "Capture local patterns a global model misses." },
        { title: "Queue-position feature", desc: "Sample position in the processing queue would sharpen predictions." },
        { title: "Staffing optimization", desc: "Align predicted slow windows with shift schedules." }],
    },
  },

  "03-patient-segmentation": {
    businessProblem: {
      headline: "What distinct patient groups exist, and how should operations adapt?",
      paragraphs: ["Each of the 2481 synthetic patients carries a visit-and-spend history. Clustering reveals 5 behavioral segments.", "Segments support targeted outreach and operational planning — frequent monitors, one-time visitors, corporate batches, and chronic-care patients behave very differently."],
      cards: [{ label: "Problem Type", value: "Unsupervised Clustering" },
        { label: "Method", value: "K-Means + PCA" },
        { label: "Silhouette", value: "0.36" }],
    },
    dataSources: {
      headline: "Four tables aggregated to one row per patient.",
      description: "Transaction-level data is rolled up into per-patient behavioral features.",
      tables: [{ name: "patients", fields: ["_id", "age", "sex", "civil_status"], note: "Demographics", primary: true },
        { name: "orders", fields: ["total_amount", "total_discount", "created_at"], note: "Spend and visit frequency" },
        { name: "order_items", fields: ["product_name"], note: "Service variety" },
        { name: "patient_services", fields: ["service_name", "created_at"], note: "Utilization" }],
    },
    methodology: {
      headline: "Aggregate, scale, cluster, profile.",
      description: "Distance-based clustering requires scaled features.",
      steps: [{ step: "01", title: "Feature Aggregation", desc: "Per patient: visit count, total spend, average spend, unique services, discount usage." },
        { step: "02", title: "Scaling", desc: "StandardScaler so no single feature dominates the distance metric." },
        { step: "03", title: "Cluster Selection", desc: "K-Means across K=3–8; K=5 chosen by silhouette and interpretability." },
        { step: "04", title: "Profiling", desc: "Each cluster profiled by behavior and mapped to a business-meaningful segment." }],
    },
    analysis: {
      headline: "Five segments emerged.",
      description: "Computed on the synthetic dataset. Cluster sizes shown below.",
      kpis: [{ value: "5", label: "Segments", sub: "K-Means", color: "#1566FF" },
        { value: "0.36", label: "Silhouette", sub: "Moderate separation", color: "#27AE60" },
        { value: "81%", label: "Variance Explained", sub: "First 2 PCA comps", color: "#475175" },
        { value: "2481", label: "Patients", sub: "Clustered", color: "#C7AA50" }],
      charts: [{ title: "Patient Count by Segment", subtitle: "Cluster sizes from K-Means", unit: "", data: [{ label: "Segment 1", value: 441 }, { label: "Segment 2", value: 1133 }, { label: "Segment 3", value: 9 }, { label: "Segment 4", value: 726 }, { label: "Segment 5", value: 172 }] }],
    },
    insights: {
      headline: "Segment-level implications.",
      items: [{ title: "One-time visitors are the largest group", desc: "The biggest cluster visits once and leaves — a clear re-engagement target." },
        { title: "Frequent monitors are high-value and sticky", desc: "A sizeable segment returns many times at modest spend each visit." },
        { title: "Corporate-batch patients separate cleanly", desc: "Bulk multi-service orders with discounts form their own cluster." },
        { title: "Reading note: a moderate silhouette", desc: "0.36 is honest, not perfect — real segmentation rarely separates cleanly, and these synthetic segments mirror that." }],
    },
    future: {
      headline: "From segments to actions.",
      items: [{ title: "Recall campaigns by segment", desc: "Chronic-care patients due for monitoring get targeted follow-ups." },
        { title: "Segment-tailored bundles", desc: "Packages matched to each segment's typical service mix." },
        { title: "Churn layer", desc: "A supervised model on top to predict who stops visiting." },
        { title: "Live assignment", desc: "Assign new patients to a segment at registration." }],
    },
  },

  "04-test-bundles": {
    businessProblem: {
      headline: "Which tests are ordered together — and what bundles does that suggest?",
      paragraphs: ["Across 10929 synthetic orders, 51% contain two or more tests.", "Association-rule mining surfaces the panels that co-occur, pointing to data-driven package design instead of intuition."],
      cards: [{ label: "Problem Type", value: "Association Rule Mining" },
        { label: "Method", value: "Apriori" },
        { label: "Strong Rules", value: "30 (lift > 1.5)" }],
    },
    dataSources: {
      headline: "Order-level service baskets across all clients.",
      description: "Each order becomes a basket of the services purchased together.",
      tables: [{ name: "order_items", fields: ["order_id", "product_name"], note: "Transaction baskets", primary: true },
        { name: "patient_services", fields: ["service_name", "patient_id"], note: "Service cross-reference" }],
    },
    methodology: {
      headline: "Baskets to rules.",
      description: "Classic market-basket analysis adapted to lab ordering.",
      steps: [{ step: "01", title: "Basket Construction", desc: "Each order_id becomes a basket of its distinct services." },
        { step: "02", title: "Encoding", desc: "One-hot transaction encoding for Apriori." },
        { step: "03", title: "Frequent Itemsets", desc: "Apriori with min_support = 0.02." },
        { step: "04", title: "Rule Generation", desc: "Rules filtered to confidence ≥ 0.4 and ranked by lift." }],
    },
    analysis: {
      headline: "Strong, sensible co-occurrence.",
      description: "Computed on the synthetic dataset.",
      kpis: [{ value: "30", label: "Strong Rules", sub: "lift > 1.5", color: "#1566FF" },
        { value: "6.5x", label: "Top Lift", sub: "BUN + Creatinine", color: "#C7AA50" },
        { value: "72%", label: "Top Confidence", sub: "Best rule", color: "#27AE60" },
        { value: "51%", label: "Multi-Test Orders", sub: "2+ services", color: "#475175" }],
      charts: [{ title: "Top Association Rules by Lift", subtitle: "How much more often pairs co-occur vs chance", unit: "x", data: [{ label: "BUN + Creatinine", value: 6.51 }, { label: "FT3 + FT4", value: 6.19 }, { label: "Complete Blood Count + Urinalysis", value: 4.61 }, { label: "HbA1c + Lipid Panel", value: 3.12 }, { label: "Fasting Blood Sugar + Lipid Panel", value: 2.9 }, { label: "Fasting Blood Sugar + HbA1c", value: 2.86 }] }],
    },
    insights: {
      headline: "Bundle implications.",
      items: [{ title: "Renal pairs are the tightest", desc: "BUN and Creatinine co-occur far above chance (lift 6.5) — a natural renal panel." },
        { title: "Thyroid tests travel together", desc: "FT3 and FT4 are almost always co-ordered — an obvious bundle." },
        { title: "A metabolic cluster emerges", desc: "Fasting glucose, HbA1c, and lipids form a recurring group." },
        { title: "Reading note: seeded co-occurrence", desc: "These pairs were built into the generator; on real data the rules would need clinical validation." }],
    },
    future: {
      headline: "From discovery to revenue.",
      items: [{ title: "Checkout suggestions", desc: "Suggest the partner test when one is ordered." },
        { title: "Branch-specific bundles", desc: "Different populations bundle differently." },
        { title: "Seasonal patterns", desc: "Some combinations may be seasonal." },
        { title: "Price optimization", desc: "Bundle pricing that maximizes uptake while holding margin." }],
    },
  },

  "05-revenue-anomalies": {
    businessProblem: {
      headline: "Are there unusual discount or revenue patterns worth a second look?",
      paragraphs: ["Across 10929 synthetic orders, two methods independently flag outliers; they agree on the clearest 150.", "The goal is an audit aid: surface transactions whose discount or amount deviates enough to warrant review."],
      cards: [{ label: "Problem Type", value: "Anomaly Detection" },
        { label: "Method", value: "Isolation Forest + Z-score" },
        { label: "Flag Rate", value: "2.5%" }],
    },
    dataSources: {
      headline: "Transaction and line-item data across all clients.",
      description: "Amounts are synthetic; ~2.5% of orders carry deliberately seeded anomalies.",
      tables: [{ name: "orders", fields: ["total_amount", "total_discount", "is_cancelled", "created_at"], note: "Transaction financials", primary: true },
        { name: "order_items", fields: ["amount", "discount"], note: "Line-item detail" }],
    },
    methodology: {
      headline: "Define normal, then find deviation.",
      description: "Two complementary detectors, combined for precision.",
      steps: [{ step: "01", title: "Feature Engineering", desc: "Discount-to-total ratio and log amount per order." },
        { step: "02", title: "Statistical Detection", desc: "Z-score on discount ratio; flag beyond 3 SD." },
        { step: "03", title: "ML Detection", desc: "Isolation Forest with contamination = 0.025." },
        { step: "04", title: "Ensemble", desc: "Treat agreement between methods as the high-confidence set." }],
    },
    analysis: {
      headline: "Clear outliers surface.",
      description: "Computed on the synthetic dataset.",
      kpis: [{ value: "2.5%", label: "Anomaly Rate", sub: "Isolation Forest", color: "#C0392B" },
        { value: "150", label: "High-Confidence", sub: "Both methods agree", color: "#27AE60" },
        { value: "150", label: "Z-score Flags", sub: "> 3 SD", color: "#1566FF" },
        { value: "5.4%", label: "Mean Discount", sub: "Across orders", color: "#C7AA50" }],
      charts: [{ title: "Detection Method Comparison", subtitle: "Orders flagged by each method", unit: "", data: [{ label: "Isolation Forest", value: 273 }, { label: "Z-score (>3 SD)", value: 150 }, { label: "Both agree", value: 150 }] }],
    },
    insights: {
      headline: "What the detectors catch.",
      items: [{ title: "Seeded outliers are caught reliably", desc: "The deliberately injected extreme discounts and amounts are recovered by both methods." },
        { title: "Agreement cuts false positives", desc: "Requiring both detectors to fire isolates the clearest cases." },
        { title: "Most flags need context", desc: "Even clear statistical outliers can be legitimate bulk orders on inspection." },
        { title: "Reading note: synthetic amounts", desc: "Amounts are fabricated, so thresholds illustrate the method rather than real finance." }],
    },
    future: {
      headline: "From detection to prevention.",
      items: [{ title: "Point-of-sale alerts", desc: "Flag unusual transactions live, not in a monthly report." },
        { title: "Cashier-level profiling", desc: "Track per-cashier discount and void rates." },
        { title: "Adaptive baselines", desc: "Shift expected discount patterns by season." },
        { title: "Audit routing", desc: "Auto-route flagged transactions to finance review." }],
    },
  },

  "06-ticket-intelligence": {
    businessProblem: {
      headline: "Can we auto-classify support tickets and understand resolution time?",
      paragraphs: ["One synthetic client carries 462 CS tickets across 5 categories with free-text descriptions.", "An NLP classifier routes tickets automatically, and resolution-time analysis exposes where priority handling breaks down."],
      cards: [{ label: "Problem Type", value: "NLP + Classification" },
        { label: "Method", value: "TF-IDF + Logistic Regression" },
        { label: "F1 (macro)", value: "0.98" }],
    },
    dataSources: {
      headline: "Synthetic CS ticket history (single client).",
      description: "Ticket descriptions, categories, priorities, and timestamps.",
      tables: [{ name: "support_tickets", fields: ["description", "category", "priority", "raised_at", "completed_at", "status"], note: "Ticket text and metadata", primary: true }],
    },
    methodology: {
      headline: "Classify the ticket, analyze the resolution.",
      description: "Text features feed the classifier; timestamps feed the resolution analysis.",
      steps: [{ step: "01", title: "Text Preprocessing", desc: "Lowercase and tokenize; medical terms preserved." },
        { step: "02", title: "Feature Extraction", desc: "TF-IDF with unigrams and bigrams, up to 2000 features." },
        { step: "03", title: "Classification", desc: "Logistic Regression over 5 categories. 75/25 split." },
        { step: "04", title: "Resolution Analysis", desc: "Resolution hours computed per ticket and grouped by priority." }],
    },
    analysis: {
      headline: "Categories classify cleanly.",
      description: "Computed on the synthetic dataset.",
      kpis: [{ value: "0.98", label: "F1 (macro)", sub: "Classifier", color: "#27AE60" },
        { value: "5", label: "Categories", sub: "Balanced", color: "#1566FF" },
        { value: "462", label: "Tickets", sub: "Synthetic client", color: "#475175" },
        { value: "4.1h", label: "P1 Median", sub: "Resolution time", color: "#C0392B" }],
      charts: [{ title: "Tickets by Category", subtitle: "Volume per category", unit: "", data: [{ label: "billing", value: 96 }, { label: "account_mgmt", value: 95 }, { label: "results_query", value: 93 }, { label: "product_setup", value: 91 }, { label: "machine_issue", value: 87 }] }, { title: "Median Resolution Time by Priority", subtitle: "Hours to resolve", unit: " h", data: [{ label: "P1", value: 4.1 }, { label: "P2", value: 11.9 }, { label: "P3", value: 6.4 }] }],
    },
    insights: {
      headline: "What the model reveals.",
      items: [{ title: "Categories are well separated", desc: "Keyword-rich descriptions make TF-IDF classification reliable (F1 0.98)." },
        { title: "P2 can lag P3", desc: "Median resolution for P2 sits above P3 in the data — a priority-handling inversion worth flagging." },
        { title: "Volume concentrates in a few categories", desc: "Machine and billing issues carry the most tickets." },
        { title: "Reading note: templated text", desc: "Descriptions are generated from category keywords, so real tickets would be messier." }],
    },
    future: {
      headline: "From manual triage to routing.",
      items: [{ title: "Auto-classify on creation", desc: "Pre-classify incoming tickets at intake." },
        { title: "SLA early warning", desc: "Alert when a ticket crosses half its SLA window." },
        { title: "Skill-based routing", desc: "Send categories to the right solver." },
        { title: "Feedback loop", desc: "Agent corrections become retraining data." }],
    },
  },

  "07-soap-nlp": {
    businessProblem: {
      headline: "What clinical patterns hide in free-text SOAP notes?",
      paragraphs: ["One synthetic clinic client carries 441 SOAP notes spanning 5 clinical topics.", "NLP turns narrative notes into structured topics and severity — making unstructured clinical text queryable."],
      cards: [{ label: "Problem Type", value: "NLP — Text Mining" },
        { label: "Method", value: "TF-IDF + Topic Modeling" },
        { label: "Topics", value: "5" }],
    },
    dataSources: {
      headline: "A dedicated soap_analytics table (single client).",
      description: "Free-text clinical notes with topic and severity structure.",
      tables: [{ name: "soap_analytics", fields: ["note_content", "note_type", "created_at"], note: "Clinical SOAP text", primary: true },
        { name: "patient_services", fields: ["service_name", "patient_id"], note: "Service context" }],
    },
    methodology: {
      headline: "Preprocess, model topics, classify severity.",
      description: "Clinical text needs domain-aware preprocessing.",
      steps: [{ step: "01", title: "Text Cleaning", desc: "Normalize whitespace; preserve clinical abbreviations." },
        { step: "02", title: "Topic Modeling", desc: "Group co-occurring clinical terms into topics." },
        { step: "03", title: "Entity Cues", desc: "Extract symptom, medication, and condition mentions." },
        { step: "04", title: "Severity Classification", desc: "Label notes mild / moderate / severe from content." }],
    },
    analysis: {
      headline: "Topics and severity emerge.",
      description: "Computed on the synthetic dataset.",
      kpis: [{ value: "5", label: "Topics", sub: "Clinical clusters", color: "#1566FF" },
        { value: "441", label: "Notes", sub: "Analyzed", color: "#475175" },
        { value: "3", label: "Severity Levels", sub: "Mild / Mod / Severe", color: "#C7AA50" },
        { value: "247", label: "Most Common", sub: "mild severity", color: "#27AE60" }],
      charts: [{ title: "Clinical Topic Distribution", subtitle: "Notes per topic", unit: "", data: [{ label: "diabetes", value: 99 }, { label: "gastro", value: 90 }, { label: "musculoskel", value: 87 }, { label: "respiratory", value: 84 }, { label: "hypertension", value: 81 }] }, { title: "Severity Breakdown", subtitle: "Notes per severity level", unit: "", data: [{ label: "mild", value: 247 }, { label: "moderate", value: 141 }, { label: "severe", value: 53 }] }],
    },
    insights: {
      headline: "What structured notes reveal.",
      items: [{ title: "Chronic-care topics dominate", desc: "Hypertension and diabetes management appear most often." },
        { title: "Respiratory complaints are common", desc: "Cough/cold/fever notes form a large acute cluster." },
        { title: "Severity skews mild", desc: "Most encounters are mild, with a small severe tail flagged for follow-up." },
        { title: "Reading note: generated notes", desc: "Note text is synthesized from topic templates, not real clinical documentation." }],
    },
    future: {
      headline: "Toward clinical intelligence.",
      items: [{ title: "ICD-10 auto-coding", desc: "Map extracted entities to billing codes." },
        { title: "Decision support", desc: "Flag severe notes lacking a documented plan." },
        { title: "Multi-client rollout", desc: "Generalize across clinics that adopt SOAP notes." },
        { title: "Fine-tuned model", desc: "A clinical language model would beat rule-based extraction." }],
    },
  },

  "08-radiology-parser": {
    businessProblem: {
      headline: "Can we structure free-text radiology impressions?",
      paragraphs: ["Two synthetic Indonesian-language clients store 624 imaging impressions as free text; 61% are normal.", "Parsing turns narrative USG and X-ray impressions into structured organ-level findings that can be queried and tracked."],
      cards: [{ label: "Problem Type", value: "Clinical NLP — Multilingual" },
        { label: "Method", value: "Regex + Multilingual NLP" },
        { label: "Normal Rate", value: "61%" }],
    },
    dataSources: {
      headline: "Imaging impressions in word_value (two clients).",
      description: "Radiology impressions stored as free text in Bahasa Indonesia with Latin organ terms.",
      tables: [{ name: "patient_service_results", fields: ["word_value", "service_name"], note: "Free-text impressions", primary: true },
        { name: "patient_services", fields: ["service_name", "status", "created_at"], note: "Service context" }],
    },
    methodology: {
      headline: "Rules first, then ML.",
      description: "Start with regex on a consistent template, validate, then layer ML.",
      steps: [{ step: "01", title: "Corpus Analysis", desc: "Catalog common phrases: 'normal', 'tidak tampak kelainan', 'tampak'." },
        { step: "02", title: "Regex Extraction", desc: "Match organ terms (hepar, ginjal, vesica) and their findings." },
        { step: "03", title: "Normal/Abnormal Rule", desc: "Classify normal when all organs read normal." },
        { step: "04", title: "Validation", desc: "Sample impressions reviewed against parsed output." }],
    },
    analysis: {
      headline: "Organ-level findings extracted.",
      description: "Computed on the synthetic dataset.",
      kpis: [{ value: "61%", label: "Normal Findings", sub: "Of all impressions", color: "#475175" },
        { value: "6", label: "Organs Tracked", sub: "Parsed", color: "#1566FF" },
        { value: "624", label: "Impressions", sub: "Parsed", color: "#27AE60" },
        { value: "2", label: "Languages", sub: "Bahasa + Latin", color: "#C7AA50" }],
      charts: [{ title: "Organ Mentions Across Impressions", subtitle: "Frequency of each organ term", unit: "", data: [{ label: "vesica", value: 162 }, { label: "ginjal", value: 156 }, { label: "pulmo", value: 131 }, { label: "cor", value: 131 }, { label: "hepar", value: 124 }, { label: "pleura", value: 55 }] }],
    },
    insights: {
      headline: "What structured radiology reveals.",
      items: [{ title: "Kidney and gallbladder lead mentions", desc: "Ginjal and vesica appear most often across impressions." },
        { title: "Templates make regex effective", desc: "Consistent phrasing means rule-based parsing covers most cases." },
        { title: "Latin terms bridge languages", desc: "Organ names stay Latin regardless of report language, easing multilingual parsing." },
        { title: "Reading note: generated impressions", desc: "Impression text is drawn from a fixed phrase set, not real radiology reports." }],
    },
    future: {
      headline: "Scaling multilingual NLP.",
      items: [{ title: "Multilingual transformer", desc: "Handle cases regex misses." },
        { title: "PACS integration", desc: "Link findings to actual images." },
        { title: "Per-patient trends", desc: "Track organ findings across visits." },
        { title: "Cross-client rollout", desc: "Adapt the parser to new templates." }],
    },
  },

  "09-cross-client-benchmark": {
    businessProblem: {
      headline: "How do the 13 clients compare operationally?",
      paragraphs: ["With 13 comparable synthetic clients, abnormal rates span 30–43% and completion sits in a tight 91–93% band.", "Benchmarking normalizes KPIs across clients so each can see where it stands against the network."],
      cards: [{ label: "Problem Type", value: "Comparative Analytics" },
        { label: "Method", value: "KPI Normalization" },
        { label: "Clients", value: "13" }],
    },
    dataSources: {
      headline: "All clients, all core tables, one view.",
      description: "Per-client KPIs computed from the shared schema and compared.",
      tables: [{ name: "patient_services", fields: ["service_name", "status", "collected_at", "locked_at"], note: "Completion and TAT", primary: true },
        { name: "orders", fields: ["total_amount", "is_cancelled"], note: "Revenue and cancellation" },
        { name: "patient_service_results", fields: ["number_value", "ref_range_min", "ref_range_max"], note: "Abnormal rate" }],
    },
    methodology: {
      headline: "Normalize, compare, contextualize.",
      description: "Comparison needs careful normalization before any ranking.",
      steps: [{ step: "01", title: "KPI Computation", desc: "Per client: completion rate, median TAT, cancellation rate, abnormal rate." },
        { step: "02", title: "Normalization", desc: "Align status vocabularies and units across clients." },
        { step: "03", title: "Comparison", desc: "Rank each client against the network distribution." },
        { step: "04", title: "Presentation", desc: "Percentile view so a client sees where it stands." }],
    },
    analysis: {
      headline: "A clear operational lens across clients.",
      description: "Computed on the synthetic dataset.",
      kpis: [{ value: "13", label: "Clients", sub: "Benchmarked", color: "#1566FF" },
        { value: "1.6x", label: "TAT Spread", sub: "Slowest vs fastest", color: "#C7AA50" },
        { value: "93%", label: "Best Completion", sub: "Top client", color: "#27AE60" },
        { value: "7.3%", label: "Avg Cancellation", sub: "Network", color: "#C0392B" }],
      charts: [{ title: "Abnormal Rate by Client", subtitle: "Top clients by abnormal result rate", unit: "%", data: [{ label: "Client 07", value: 42.9 }, { label: "Client 06", value: 42.2 }, { label: "Client 10", value: 41.4 }, { label: "Client 08", value: 39.3 }, { label: "Client 09", value: 38.6 }, { label: "Client 11", value: 37.9 }, { label: "Client 02", value: 36.6 }, { label: "Client 01", value: 34.5 }] }],
    },
    insights: {
      headline: "What the comparison reveals.",
      items: [{ title: "Abnormal rates vary by client", desc: "A 13-point spread separates the highest and lowest clients." },
        { title: "Completion is consistent", desc: "Clients cluster tightly on completion, so differences live elsewhere." },
        { title: "Turnaround spreads widest", desc: "A 1.6x gap in median TAT is the clearest differentiator." },
        { title: "Reading note: synthetic clients", desc: "Client-level differences are engineered offsets, useful to demonstrate the benchmarking method." }],
    },
    future: {
      headline: "From showcase to product.",
      items: [{ title: "Benchmark intelligence", desc: "Tell each client how it compares to the network." },
        { title: "Automated monthly reports", desc: "Per-client percentile rankings on a schedule." },
        { title: "Peer-group matching", desc: "Compare to similar-sized peers, not the whole network." },
        { title: "Trend alerts", desc: "Flag clients whose metrics deteriorate over time." }],
    },
  },

};
