import type { ProjectMeta } from "@/lib/types";

export const projects: ProjectMeta[] = [
  {
    slug: "01-abnormal-results",
    number: 1,
    title: "Abnormal Lab Result Predictor",
    tagline: "Classify lab results as normal or abnormal from patient age, test type, and site.",
    difficulty: "Beginner",
    status: "complete",
    clients: ["All 13 Sites"],
    tables: ["patients", "patient_service_results", "patient_services"],
    techniques: ["Logistic Regression", "Random Forest", "ROC-AUC"],
    keyMetric: { value: "0.78", label: "AUC Score" },
    color: "bg-[#ECF2FE]",
  },
  {
    slug: "02-turnaround-time",
    number: 2,
    title: "Lab Turnaround Time Predictor",
    tagline: "Predict service turnaround from weekday, hour, branch, and test type.",
    difficulty: "Beginner",
    status: "complete",
    clients: ["All 13 Sites"],
    tables: ["patient_services", "patients", "orders"],
    techniques: ["Random Forest Regressor", "Datetime Features", "MAE / R\u00B2"],
    keyMetric: { value: "0.79", label: "TAT Model R\u00B2" },
    color: "bg-[#ECF2FE]",
  },
  {
    slug: "03-patient-segmentation",
    number: 3,
    title: "Patient Segmentation",
    tagline: "Cluster patients into behavioral segments from visit and spend history.",
    difficulty: "Intermediate",
    status: "complete",
    clients: ["All 13 Sites"],
    tables: ["patients", "orders", "order_items", "patient_services"],
    techniques: ["K-Means", "StandardScaler", "PCA"],
    keyMetric: { value: "5", label: "Segments Found" },
    color: "bg-[#ECF2FE]",
  },
  {
    slug: "04-test-bundles",
    number: 4,
    title: "Test Bundle Analysis",
    tagline: "Mine which tests are ordered together to inform package design.",
    difficulty: "Beginner",
    status: "complete",
    clients: ["All 13 Sites"],
    tables: ["order_items", "patient_services"],
    techniques: ["Apriori", "Association Rules", "Lift / Confidence"],
    keyMetric: { value: "51%", label: "Orders Bundled" },
    color: "bg-[#ECF2FE]",
  },
  {
    slug: "05-revenue-anomalies",
    number: 5,
    title: "Revenue & Discount Anomaly Detection",
    tagline: "Surface unusual discount and revenue patterns across orders.",
    difficulty: "Intermediate",
    status: "complete",
    clients: ["All 13 Sites"],
    tables: ["orders", "order_items"],
    techniques: ["Isolation Forest", "Z-score", "Ensemble Agreement"],
    keyMetric: { value: "2.5%", label: "Anomaly Rate" },
    color: "bg-[#F7F3DF]",
  },
  {
    slug: "06-ticket-intelligence",
    number: 6,
    title: "Support Ticket Intelligence",
    tagline: "Classify CS tickets into categories and analyze resolution time by priority.",
    difficulty: "Intermediate",
    status: "complete",
    clients: ["Site 03 (CS)"],
    tables: ["support_tickets"],
    techniques: ["TF-IDF", "Logistic Regression", "F1-macro"],
    keyMetric: { value: "0.98", label: "Classification F1" },
    color: "bg-[#F7F3DF]",
  },
  {
    slug: "07-soap-nlp",
    number: 7,
    title: "SOAP Notes NLP Analysis",
    tagline: "Extract clinical topics and severity from free-text SOAP notes.",
    difficulty: "Advanced",
    status: "complete",
    clients: ["Site 11 (Clinic)"],
    tables: ["soap_analytics", "patient_services"],
    techniques: ["TF-IDF", "Topic Modeling", "Severity Classification"],
    keyMetric: { value: "5", label: "Clinical Topics" },
    color: "bg-[#FCE4EC]",
  },
  {
    slug: "08-radiology-parser",
    number: 8,
    title: "Radiology Impression Parser",
    tagline: "Parse multilingual radiology impressions into structured organ-level findings.",
    difficulty: "Advanced",
    status: "complete",
    clients: ["Sites 02 & 13 (Imaging)"],
    tables: ["patient_service_results"],
    techniques: ["Regex Extraction", "Multilingual NLP", "Bahasa Indonesia"],
    keyMetric: { value: "61%", label: "Normal Findings" },
    color: "bg-[#FCE4EC]",
  },
  {
    slug: "09-cross-client-benchmark",
    number: 9,
    title: "Cross-Site Operational Benchmarking",
    tagline: "Compare operational KPIs across 13 synthetic healthcare sites.",
    difficulty: "Intermediate",
    status: "complete",
    clients: ["All 13 Sites"],
    tables: ["patient_services", "orders", "patient_service_results"],
    techniques: ["Statistical Comparison", "KPI Normalization", "Percentile Ranking"],
    keyMetric: { value: "13", label: "Sites Benchmarked" },
    color: "bg-[#F7F3DF]",
  },
];
